import React from 'react';
import './css/about.css';


const About = () => (
  <body>
      <br />
    <div className="row our-data-header">
      <h4>About Our Wind Data</h4>
    </div>
    <div className='container data-info'>
      <div className="row">
        <div className="col-4">
          <div className="card">
            <div className="card-body">
              <h3 className="card-title">Wind Speed</h3>
              <p className="card-text">Wind speed is a measure of the speed of air movement relative to a fixed point on the Earth.
               It expresses the strength of the horizontal movement of the air, measured in Meters/Second. Our data
               is from NASA's 10m above surface wind speed measurement, time averaged over the last decade.</p>
              <a href="https://disc.gsfc.nasa.gov/information/glossary?keywords=giovanni%20measurements&title=Giovanni%20Measurement%20Definitions:%20Wind" class="btn btn-primary">See on NASA</a>
            </div>
          </div>
        </div>
        <div className="col-4">
          <div className="card">
            <div className="card-body">
              <h3 className="card-title">Air Temperature</h3>
              <p className="card-text">Air temperature is the measurement of the atmospheric kinetic energy at a given location
               in the atmosphere, measured in degrees Kelvin. Our data is from NASA's 10 meter above ground air temperature
               measurement time averaged over the last decade.</p>
              <a href="https://disc.gsfc.nasa.gov/information/glossary?keywords=giovanni%20measurements&title=Giovanni%20Measurement%20Definitions:%20Air%20Temperature" class="btn btn-primary">See on NASA</a>
            </div>
          </div>
        </div>
        <div className="col-4">
          <div className="card">
            <div className="card-body">
              <h3 className="card-title">Wind Stress</h3>
              <p className="card-text">Wind stress magnitude is the amount of force on a surface generated by winds.  It is a function
               of drag, air density, and wind velocity, and has units of Newtons per square meter (N/m2). Our data is from NASA's wind stress magnitude 
               measurement, time averaged over the last decade</p>
              <a href="https://disc.gsfc.nasa.gov/information/glossary?keywords=giovanni%20measurements&title=Giovanni%20Measurement%20Definitions:%20Wind" className="btn btn-primary">See on NASA</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div className='container d-flex justify-content-center'>
      <div className='img'></div>
      <div className='text-box'>
        <h3 className="space">Our Team</h3>
        <p className="bigger_text">Windivision's team consists of Ilhwan Song, Miles Ednie, Peter Krumhpolz, and Sydney Hannert. We are a group of hardworking, focused individuals, hoping to provide a useful platform to display wind data for the purpose of finding new locations for wind turbines. </p>
      </div>
    </div>
    <div className="end"></div>
  </body>
);

export default About;